# -*- coding: utf-8 -*-
"""Program2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PM74EqKCED42_zlK8jSbQRNFFQ_1sJbq
"""

from os import name

## Question: Design a base class Employee with private attributes for name,
## employee_id, and salary. Create subclasses FullTimeEmployee and
## PartTimeEmployee that inherit from Employee and add their respective attributes
## and methods. Include a method to calculate annual salary in both subclasses and
## ensure proper access to private variables.
## [Hint/Sample Output: FullTimeEmployee(Name: Alice Johnson, ID: F123,
## Salary: 5000, Annual Bonus: 2000)
## Annual Salary: 62000
## PartTimeEmployee(Name: Bob Smith, ID: P456, Hourly Rate: 20, Hours Per
## Week: 25)
## Annual Salary: 26000

class Employee:
  def __init__(self,name,id,salary):
    self.name=name
    self.id=id
    self.salary=salary

class FullTimeEmployee(Employee):
  def __init__(self,name,id,salary,Annual_bonus):
    self.name=name
    self.id=id
    self.salary=salary
    self.Annual_bonus=Annual_bonus

  def annualSalary(self):
      annualSal=self.Annual_bonus+12*self.salary
      print("Annual Salary : ",annualSal)


obj=FullTimeEmployee("Alex","A123",5000,2000)
obj.annualSalary()